version: "3.3"
services:
    vidl-web:
        build: ./web
        container_name: vidl-web
        restart_policy:
            condition: on-failure
        ports:
            - 80:80
        volumes:
            - ./web/src:/usr/src/app
        environment:
            - "NODEJS_VERSION=8.6.0"
            - "VIDL_ENV=dev"
